server:
  port: 8801
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    leaseExpirationDurationInSeconds: 15
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8800/eureka/
